apiVersion: v1
kind: Pod
metadata:
  name: cluster20219b
spec:
  securityContext:
    runAsUser: 270999
    runAsGroup: 1132
  restartPolicy: Never
  containers:
    - name: cluster20219b-pod
      image: ghcr.io/stmorse/dtm:latest
      resources:
        requests:
          memory: '128Gi'
          # nvidia.com/gpu: '1'
          cpu: '24'
        limits:
          memory: '128Gi'
          # nvidia.com/gpu: '1'
          cpu: '24'
      command: ['/bin/sh']
      args:
        - '-c'
        - |
          echo "Running container..."
          cd /sciclone/geograd/stmorse/dtm/src
          python3 -u 2a_cluster_s.py \
            --subpath mbkm_50 \
            --start-year 2021 \
            --end-year 2021 \
            --start-month 9 \
            --end-month 9 \
            --n-clusters 50 \
            --top-k 100 \
            --top-m 20 \
            --max-df 0.3 \
            > ../logs/cluster20219b_out.log 2>&1
          # sleep infinity
      volumeMounts:
        - name: data
          mountPath: /sciclone/data10/twford/reddit/reddit
        - name: results
          mountPath: /sciclone/geograd/stmorse
  volumes:
    - name: data
      nfs:
        server: 128.239.56.30
        path: /sciclone/data10/twford/reddit/reddit
    - name: results
      nfs:
        server: 128.239.59.144
        path: /sciclone/geograd/stmorse
