apiVersion: v1
kind: Pod
metadata:
  name: dev
spec:
  securityContext:
    runAsUser: 270999
    runAsGroup: 1132
  containers:
    - name: dev-pod
      # image: docker.io/stmorse314/transformers-torch:latest
      image: ghcr.io/stmorse/dtm:latest
      resources:
        requests:
          memory: '128Gi'
          nvidia.com/gpu: '1'
        limits:
          memory: '128Gi'
          nvidia.com/gpu: '1'
      command: ['/bin/sh']
      args:
        - '-c'
        - |
          echo "Running container..."   # pod is for dev'ing scripts, run indef
          sleep infinity
      env:
        - name: HF_HOME
          value: '/sciclone/home/stmorse/.cache/huggingface/hub'
      volumeMounts:
        - name: home
          mountPath: /sciclone/home/stmorse
        - name: data
          mountPath: /sciclone/data10/twford/reddit/reddit
        - name: results
          mountPath: /sciclone/geograd/stmorse
  volumes:
    - name: home
      nfs:
        server: 128.239.56.166
        path: /sciclone/home/stmorse
    - name: data
      nfs:
        server: 128.239.56.30
        path: /sciclone/data10/twford/reddit/reddit
    - name: results
      nfs:
        server: 128.239.59.144
        path: /sciclone/geograd/stmorse