apiVersion: v1
kind: Pod
metadata:
  name: dev
spec:
  securityContext:
    runAsUser: 270999
    runAsGroup: 1132
  affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - gu07.sciclone.wm.edu
                - gu08.sciclone.wm.edu
                - gu09.sciclone.wm.edu
                - gu10.sciclone.wm.edu
                - gu11.sciclone.wm.edu
                - gu12.sciclone.wm.edu
                - gu13.sciclone.wm.edu
                - gu14.sciclone.wm.edu
                - gu15.sciclone.wm.edu
                - gu16.sciclone.wm.edu
                - gu17.sciclone.wm.edu
                - gu18.sciclone.wm.edu
                - gu19.sciclone.wm.edu
  containers:
    - name: dev-pod
      #image: docker.io/pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime
      image: ghcr.io/stmorse/dtm:latest
      # image: docker.io/busybox
      resources:
        requests:
          memory: '64Gi'
          nvidia.com/gpu: '1'
          cpu: '4'
        limits:
          memory: '64Gi'
          nvidia.com/gpu: '1'
          cpu: '4'
      command: ['/bin/bash']
      args:
        - '-c'
        - |
          echo "Running container..."   # pod is for dev'ing scripts, run indef
          cd /sciclone/geograd/stmorse/dtm
          sleep infinity
      env:
        - name: HF_HOME
          value: '/sciclone/home/stmorse/.cache/huggingface'
        - name: NUMBA_CACHE_DIR   # for umap
          value: /tmp/numba_cache
      volumeMounts:
        - name: home
          mountPath: /sciclone/home/stmorse
        - name: data
          mountPath: /sciclone/data10/twford/reddit/reddit
        - name: results
          mountPath: /sciclone/proj-ds/geograd/stmorse
  volumes:
    - name: home
      nfs:
        server: 128.239.56.166
        path: /sciclone/home/stmorse
    - name: data
      nfs:
        server: 128.239.56.30
        path: /sciclone/data10/twford/reddit/reddit
    - name: results
      nfs:
        server: 192.168.59.144  # IB
        path: /sciclone/proj-ds/geograd/stmorse
