apiVersion: v1
kind: Pod
metadata:
  name: vol
spec:
  securityContext:
    runAsUser: 270999
    runAsGroup: 1132
  restartPolicy: Never
  # nodeSelector:
  #   kubernetes.io/hostname: grace.sciclone.wm.edu
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - gu07.sciclone.wm.edu
            - gu08.sciclone.wm.edu
            - gu09.sciclone.wm.edu
            - gu10.sciclone.wm.edu
            - gu11.sciclone.wm.edu
            - gu12.sciclone.wm.edu
            - gu13.sciclone.wm.edu
            - gu14.sciclone.wm.edu
            - gu15.sciclone.wm.edu
            - gu16.sciclone.wm.edu
            - gu17.sciclone.wm.edu
            - gu18.sciclone.wm.edu
            - gu19.sciclone.wm.edu
  containers:
    - name: vol-pod
      image: busybox
      resources:
        requests:
          memory: '1Gi'
          # nvidia.com/gpu: '1'
          cpu: '1'
        limits:
          memory: '1Gi'
          # nvidia.com/gpu: '1'
          cpu: '1'
      command: ['/bin/sh']
      args:
        - '-c'
        - |
          echo "Running container..."
          sleep infinity
      volumeMounts:
        - name: home
          mountPath: /sciclone/home/stmorse
        - name: data
          mountPath: /sciclone/data10/twford/reddit/reddit
        - name: results
          mountPath: /sciclone/proj-ds/geograd/stmorse
  volumes:
    - name: home
      nfs:
        server: 128.239.56.166
        path: /sciclone/home/stmorse
    - name: data
      nfs:
        server: 128.239.56.30
        path: /sciclone/data10/twford/reddit/reddit
    - name: results
      nfs:
        server: 192.168.59.144  # IB
        # server: 128.239.59.144
        path: /sciclone/proj-ds/geograd/stmorse
